spring:
  application:
    name: auth-ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:authuser}
    password: ${SPRING_DATASOURCE_PASSWORD:authpass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: none
      password: none

jwt:
  secret: dGhpc19pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLWp3dC1hdXRo
  expiration-ms: 3600000

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true
