spring:
  application:
    name: empleado-ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/empleadodb}
    username: ${SPRING_DATASOURCE_USERNAME:empleadouser}
    password: ${SPRING_DATASOURCE_PASSWORD:empleadopass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true
