spring:
  application:
    name: gasto-ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/gastodb}
    username: ${SPRING_DATASOURCE_USERNAME:gastouser}
    password: ${SPRING_DATASOURCE_PASSWORD:gastopass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true

